# Generated by Django 3.2.8 on 2024-12-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(max_length=100)),
                ('city_or_region', models.CharField(max_length=100)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('tour_languages', models.TextField(help_text='Comma-separated list of languages')),
                ('presentation', models.TextField()),
                ('photo', models.ImageField(upload_to='pics/')),
                ('certified_guide', models.BooleanField(default=False)),
                ('guide_card', models.FileField(blank=True, null=True, upload_to='pics/')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
