# Generated by Django 5.1.2 on 2024-12-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_message_delete_contactmessage_alter_destination_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
