# Generated by Django 5.1.2 on 2025-01-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('time_slots', models.CharField(blank=True, max_length=255, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.guide')),
            ],
        ),
    ]
