# Generated by Django 5.1.2 on 2025-01-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_message_delete_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
